
title: Basel's Blog
email: mrbasel555@gmail.com
author: Basel
description: >- # this means to ignore newlines until "baseurl:"
   CS student and programmer. Writing about software and other things that interest me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: baselalnassr
github_username:  mrbasel

# Build settings
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/